development:
  adapter: mysql2
  database: phonebook_development
  host: 10.110.111.94
  username: root
  password: 'admin'
  encoding: utf8
  port: 3306

test:
  adapter: mysql2
  database: phonebook_test
  host: 10.110.111.94
  username: root
  password: 'admin'
  encoding: utf8
  port: 3306